// Command soundgen turns the versioned Java sound registry and Geyser's
// authoritative sound-name mappings into a deterministic Go lookup table.
// Source payloads stay outside this repository; only the generated table and
// source hashes are committed.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type javaSound struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type geyserSound struct {
	PlaySound string `json:"playsound_mapping"`
}

func main() {
	javaPath := flag.String("java-sounds", "", "minecraft-data sounds.json for the Java protocol")
	geyserPath := flag.String("geyser-sounds", "", "Geyser mappings sounds.json")
	outPath := flag.String("out", "", "generated Go file")
	flag.Parse()
	if *javaPath == "" || *geyserPath == "" || *outPath == "" {
		panic("usage: soundgen -java-sounds path -geyser-sounds path -out path")
	}

	javaBytes, err := os.ReadFile(*javaPath)
	if err != nil {
		panic(fmt.Errorf("read Java sounds: %w", err))
	}
	var raw []javaSound
	if err := json.Unmarshal(javaBytes, &raw); err != nil {
		panic(fmt.Errorf("decode Java sounds: %w", err))
	}
	names := make([]string, len(raw))
	for _, sound := range raw {
		if sound.ID <= 0 || sound.ID > len(raw) || sound.Name == "" {
			panic(fmt.Sprintf("invalid Java sound id=%d name=%q", sound.ID, sound.Name))
		}
		index := sound.ID - 1
		if names[index] != "" {
			panic(fmt.Sprintf("duplicate Java sound id %d", sound.ID))
		}
		names[index] = sound.Name
	}
	for id, name := range names {
		if name == "" {
			panic(fmt.Sprintf("Java sound id %d is missing", id+1))
		}
	}

	geyserBytes, err := os.ReadFile(*geyserPath)
	if err != nil {
		panic(fmt.Errorf("read Geyser sounds: %w", err))
	}
	var mappings map[string]geyserSound
	if err := json.Unmarshal(geyserBytes, &mappings); err != nil {
		panic(fmt.Errorf("decode Geyser sounds: %w", err))
	}
	playNames := make(map[string]string, len(names))
	for _, name := range names {
		if mapping := mappings[name].PlaySound; mapping != "" {
			playNames[name] = mapping
		}
	}

	output := render(names, playNames, sha256Hex(javaBytes), sha256Hex(geyserBytes))
	formatted, err := format.Source([]byte(output))
	if err != nil {
		panic(fmt.Errorf("format generated Go: %w", err))
	}
	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("Java sounds=%d mapped playsounds=%d\n", len(names), len(playNames))
}

func sha256Hex(value []byte) string {
	hash := sha256.Sum256(value)
	return hex.EncodeToString(hash[:])
}

func render(names []string, playNames map[string]string, javaHash, geyserHash string) string {
	var builder strings.Builder
	fmt.Fprintln(&builder, "// Code generated by cmd/soundgen; DO NOT EDIT.")
	fmt.Fprintf(&builder, "// Java sound source SHA-256: %s\n", javaHash)
	fmt.Fprintf(&builder, "// Geyser sound mapping source SHA-256: %s\n", geyserHash)
	fmt.Fprintf(&builder, "// Sound coverage: %d Java registry entries, %d playsound mappings.\n\n", len(names), len(playNames))
	fmt.Fprintln(&builder, "package data")
	fmt.Fprintln(&builder)
	fmt.Fprintln(&builder, `import "strings"`)
	fmt.Fprintln(&builder)
	fmt.Fprintf(&builder, "const Java1214SoundCount = %d\n\n", len(names))
	fmt.Fprintln(&builder, "var Java1214SoundNames = [...]string{")
	for i, name := range names {
		if i%3 == 0 {
			builder.WriteString("\t")
		}
		fmt.Fprintf(&builder, "%q, ", name)
		if i%3 == 2 {
			builder.WriteByte('\n')
		}
	}
	if len(names)%3 != 0 {
		builder.WriteByte('\n')
	}
	builder.WriteString("}\n\n")
	fmt.Fprintln(&builder, "var Java1214SoundPlayNames = map[string]string{")
	keys := make([]string, 0, len(playNames))
	for name := range playNames {
		keys = append(keys, name)
	}
	// The input JSON object order is not a source contract; sort keys so the
	// generated file is stable across Go versions and JSON encoders.
	sort.Strings(keys)
	for _, name := range keys {
		fmt.Fprintf(&builder, "\t%q: %q,\n", name, playNames[name])
	}
	builder.WriteString("}\n\n")
	builder.WriteString(`// Java1214SoundName resolves the registry holder ID used by the
// 1.21.4 sound packets. IDs in the wire holder are one-based.
func Java1214SoundName(id int32) (string, bool) {
	if id <= 0 || int64(id) > int64(len(Java1214SoundNames)) {
		return "", false
	}
	return Java1214SoundNames[id-1], true
}

// BedrockSoundName applies the Geyser playsound mapping and falls back to the
// namespace-free Java identifier for custom or unmapped sounds.
func BedrockSoundName(name string) string {
	name = strings.TrimPrefix(name, "minecraft:")
	if mapped := Java1214SoundPlayNames[name]; mapped != "" {
		return mapped
	}
	return name
}
`)
	return builder.String()
}
