package data

import (
	"fmt"
	"io"
	"strconv"
)

// WriteGo emits a deterministic Go source file containing a Catalog. It is
// intentionally a generator output, not a checked-in copy of Mojang or
// Cloudburst payloads; rebuild it from a pinned source checkout.
func WriteGo(w io.Writer, packageName string, catalog Catalog) error {
	if packageName == "" {
		return fmt.Errorf("data: generated package name is empty")
	}
	if err := catalog.Validate(); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "// Code generated by cmd/registrygen; DO NOT EDIT.\n\npackage %s\n\n", packageName); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "var GeneratedCatalog = Catalog{\n\tVersion: %s,\n\tSource: SourceManifest{Name: %s, Files: []SourceFile{\n", strconv.Quote(catalog.Version), strconv.Quote(catalog.Source.Name)); err != nil {
		return err
	}
	for _, source := range catalog.Source.Files {
		if _, err := fmt.Fprintf(w, "\t\t{Name: %s, SHA256: %s},\n", strconv.Quote(source.Name), strconv.Quote(source.SHA256)); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\t}},\n\tItems: []ItemDefinition{\n"); err != nil {
		return err
	}
	for _, item := range catalog.Items {
		if _, err := fmt.Fprintf(w, "\t\t{Name: %s, RuntimeID: %d, Version: %d, ComponentBased: %t, SourceJSON: %s},\n", strconv.Quote(item.Name), item.RuntimeID, item.Version, item.ComponentBased, strconv.Quote(item.SourceJSON)); err != nil {
			return err
		}
	}
	if _, err := io.WriteString(w, "\t},\n\tBlocks: []BlockDefinition{\n"); err != nil {
		return err
	}
	for _, block := range catalog.Blocks {
		if _, err := fmt.Fprintf(w, "\t\t{Name: %s, BlockStateHash: %d, TranslationKey: %s, IsSolid: %t, Hardness: %g, ExplosionResistance: %g, Friction: %g, RequiresCorrectToolForDrops: %t, LightEmission: %d, SourceJSON: %s},\n", strconv.Quote(block.Name), block.BlockStateHash, strconv.Quote(block.TranslationKey), block.IsSolid, block.Hardness, block.ExplosionResistance, block.Friction, block.RequiresCorrectToolForDrops, block.LightEmission, strconv.Quote(block.SourceJSON)); err != nil {
			return err
		}
	}
	_, err := io.WriteString(w, "\t},\n}\n")
	return err
}
