// Code generated by cmd/registrygen; DO NOT EDIT.
// Java entity source: minecraft-data entities.json for Java 1.21.4 (protocol 769).
// Java entity source SHA-256: 97df613b089e7e703f52cd28db5cdcae16dc36cfcd5ac8720b4a31c1fd855f89
// Geyser source repository: https://github.com/GeyserMC/Geyser
// Geyser source commit: 8f6a9d20b05c302282f9496314b7c18cf6d4cc53
// Geyser VanillaEntities.java source SHA-256: 137361ddbd62f449263fc59f9a0a07d0988b07c991b6200466007af874cc9c8c
// Generated entries: 146; explicit network-definition omissions: 3.

package data

import "strings"

// EntityDisplayDimensions contains the Java hitbox dimensions Geyser uses when
// projecting a Bedrock mob-spawner display actor.
type EntityDisplayDimensions struct {
	JavaIdentifier    string
	BedrockIdentifier string
	Width             float32
	Height            float32
}

var Java1214EntityDisplayDimensions = []EntityDisplayDimensions{
	{JavaIdentifier: "minecraft:acacia_boat", BedrockIdentifier: "minecraft:acacia_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:acacia_chest_boat", BedrockIdentifier: "minecraft:acacia_chest_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:allay", BedrockIdentifier: "minecraft:allay", Width: 0.35, Height: 0.6},
	{JavaIdentifier: "minecraft:area_effect_cloud", BedrockIdentifier: "minecraft:area_effect_cloud", Width: 1, Height: 0.5},
	{JavaIdentifier: "minecraft:armadillo", BedrockIdentifier: "minecraft:armadillo", Width: 0.7, Height: 0.65},
	{JavaIdentifier: "minecraft:armor_stand", BedrockIdentifier: "minecraft:armor_stand", Width: 0.5, Height: 1.975},
	{JavaIdentifier: "minecraft:arrow", BedrockIdentifier: "minecraft:arrow", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:axolotl", BedrockIdentifier: "minecraft:axolotl", Width: 0.7, Height: 0.42},
	{JavaIdentifier: "minecraft:bamboo_chest_raft", BedrockIdentifier: "minecraft:bamboo_chest_raft", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:bamboo_raft", BedrockIdentifier: "minecraft:bamboo_raft", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:bat", BedrockIdentifier: "minecraft:bat", Width: 0.5, Height: 0.9},
	{JavaIdentifier: "minecraft:bee", BedrockIdentifier: "minecraft:bee", Width: 0.6, Height: 0.6},
	{JavaIdentifier: "minecraft:birch_boat", BedrockIdentifier: "minecraft:birch_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:birch_chest_boat", BedrockIdentifier: "minecraft:birch_chest_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:blaze", BedrockIdentifier: "minecraft:blaze", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:bogged", BedrockIdentifier: "minecraft:bogged", Width: 0.6, Height: 1.99},
	{JavaIdentifier: "minecraft:breeze", BedrockIdentifier: "minecraft:breeze", Width: 0.6, Height: 1.77},
	{JavaIdentifier: "minecraft:breeze_wind_charge", BedrockIdentifier: "minecraft:breeze_wind_charge_projectile", Width: 0.3125, Height: 0.3125},
	{JavaIdentifier: "minecraft:camel", BedrockIdentifier: "minecraft:camel", Width: 1.7, Height: 2.375},
	{JavaIdentifier: "minecraft:cat", BedrockIdentifier: "minecraft:cat", Width: 0.3, Height: 0.35},
	{JavaIdentifier: "minecraft:cave_spider", BedrockIdentifier: "minecraft:cave_spider", Width: 0.7, Height: 0.5},
	{JavaIdentifier: "minecraft:cherry_boat", BedrockIdentifier: "minecraft:cherry_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:cherry_chest_boat", BedrockIdentifier: "minecraft:cherry_chest_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:chest_minecart", BedrockIdentifier: "minecraft:chest_minecart", Width: 0.98, Height: 0.7},
	{JavaIdentifier: "minecraft:chicken", BedrockIdentifier: "minecraft:chicken", Width: 0.4, Height: 0.7},
	{JavaIdentifier: "minecraft:cod", BedrockIdentifier: "minecraft:cod", Width: 0.5, Height: 0.25},
	{JavaIdentifier: "minecraft:command_block_minecart", BedrockIdentifier: "minecraft:command_block_minecart", Width: 0.98, Height: 0.7},
	{JavaIdentifier: "minecraft:cow", BedrockIdentifier: "minecraft:cow", Width: 0.9, Height: 1.4},
	{JavaIdentifier: "minecraft:creaking", BedrockIdentifier: "minecraft:creaking", Width: 0.9, Height: 2.7},
	{JavaIdentifier: "minecraft:creeper", BedrockIdentifier: "minecraft:creeper", Width: 0.6, Height: 1.7},
	{JavaIdentifier: "minecraft:dark_oak_boat", BedrockIdentifier: "minecraft:dark_oak_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:dark_oak_chest_boat", BedrockIdentifier: "minecraft:dark_oak_chest_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:dolphin", BedrockIdentifier: "minecraft:dolphin", Width: 0.9, Height: 0.6},
	{JavaIdentifier: "minecraft:donkey", BedrockIdentifier: "minecraft:donkey", Width: 1.3965, Height: 1.6},
	{JavaIdentifier: "minecraft:dragon_fireball", BedrockIdentifier: "minecraft:dragon_fireball", Width: 1, Height: 1},
	{JavaIdentifier: "minecraft:drowned", BedrockIdentifier: "minecraft:drowned", Width: 0.6, Height: 1.95},
	{JavaIdentifier: "minecraft:egg", BedrockIdentifier: "minecraft:egg", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:elder_guardian", BedrockIdentifier: "minecraft:elder_guardian", Width: 1.9975, Height: 1.9975},
	{JavaIdentifier: "minecraft:end_crystal", BedrockIdentifier: "minecraft:ender_crystal", Width: 2, Height: 2},
	{JavaIdentifier: "minecraft:ender_dragon", BedrockIdentifier: "minecraft:ender_dragon", Width: 0, Height: 0},
	{JavaIdentifier: "minecraft:ender_pearl", BedrockIdentifier: "minecraft:ender_pearl", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:enderman", BedrockIdentifier: "minecraft:enderman", Width: 0.6, Height: 2.9},
	{JavaIdentifier: "minecraft:endermite", BedrockIdentifier: "minecraft:endermite", Width: 0.4, Height: 0.3},
	{JavaIdentifier: "minecraft:evoker", BedrockIdentifier: "minecraft:evoker", Width: 0.6, Height: 1.95},
	{JavaIdentifier: "minecraft:evoker_fangs", BedrockIdentifier: "minecraft:evocation_fang", Width: 0.5, Height: 0.8},
	{JavaIdentifier: "minecraft:experience_bottle", BedrockIdentifier: "minecraft:xp_bottle", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:experience_orb", BedrockIdentifier: "minecraft:xp_orb", Width: 0, Height: 0},
	{JavaIdentifier: "minecraft:eye_of_ender", BedrockIdentifier: "minecraft:eye_of_ender_signal", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:falling_block", BedrockIdentifier: "minecraft:falling_block", Width: 0.98, Height: 0.98},
	{JavaIdentifier: "minecraft:fireball", BedrockIdentifier: "minecraft:fireball", Width: 1, Height: 1},
	{JavaIdentifier: "minecraft:firework_rocket", BedrockIdentifier: "minecraft:fireworks_rocket", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:fishing_bobber", BedrockIdentifier: "minecraft:fishing_hook", Width: 0, Height: 0},
	{JavaIdentifier: "minecraft:fox", BedrockIdentifier: "minecraft:fox", Width: 0.6, Height: 0.7},
	{JavaIdentifier: "minecraft:frog", BedrockIdentifier: "minecraft:frog", Width: 0.5, Height: 0.5},
	{JavaIdentifier: "minecraft:furnace_minecart", BedrockIdentifier: "minecraft:furnace_minecart", Width: 0.98, Height: 0.7},
	{JavaIdentifier: "minecraft:ghast", BedrockIdentifier: "minecraft:ghast", Width: 4, Height: 4},
	{JavaIdentifier: "minecraft:giant", BedrockIdentifier: "minecraft:giant", Width: 1.6, Height: 1.8},
	{JavaIdentifier: "minecraft:glow_item_frame", BedrockIdentifier: "minecraft:glow_item_frame", Width: 0, Height: 0},
	{JavaIdentifier: "minecraft:glow_squid", BedrockIdentifier: "minecraft:glow_squid", Width: 0.8, Height: 0.8},
	{JavaIdentifier: "minecraft:goat", BedrockIdentifier: "minecraft:goat", Width: 0.9, Height: 1.3},
	{JavaIdentifier: "minecraft:guardian", BedrockIdentifier: "minecraft:guardian", Width: 0.85, Height: 0.85},
	{JavaIdentifier: "minecraft:hoglin", BedrockIdentifier: "minecraft:hoglin", Width: 1.3965, Height: 1.4},
	{JavaIdentifier: "minecraft:hopper_minecart", BedrockIdentifier: "minecraft:hopper_minecart", Width: 0.98, Height: 0.7},
	{JavaIdentifier: "minecraft:horse", BedrockIdentifier: "minecraft:horse", Width: 1.3965, Height: 1.6},
	{JavaIdentifier: "minecraft:husk", BedrockIdentifier: "minecraft:husk", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:illusioner", BedrockIdentifier: "minecraft:illusioner", Width: 0.6, Height: 1.95},
	{JavaIdentifier: "minecraft:interaction", BedrockIdentifier: "minecraft:interaction", Width: 1, Height: 1},
	{JavaIdentifier: "minecraft:iron_golem", BedrockIdentifier: "minecraft:iron_golem", Width: 1.4, Height: 2.7},
	{JavaIdentifier: "minecraft:item", BedrockIdentifier: "minecraft:item", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:item_frame", BedrockIdentifier: "minecraft:item_frame", Width: 0, Height: 0},
	{JavaIdentifier: "minecraft:jungle_boat", BedrockIdentifier: "minecraft:jungle_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:jungle_chest_boat", BedrockIdentifier: "minecraft:jungle_chest_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:leash_knot", BedrockIdentifier: "minecraft:leash_knot", Width: 0.375, Height: 0.5},
	{JavaIdentifier: "minecraft:lightning_bolt", BedrockIdentifier: "minecraft:lightning_bolt", Width: 0, Height: 0},
	{JavaIdentifier: "minecraft:llama", BedrockIdentifier: "minecraft:llama", Width: 0.9, Height: 1.87},
	{JavaIdentifier: "minecraft:llama_spit", BedrockIdentifier: "minecraft:llama_spit", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:magma_cube", BedrockIdentifier: "minecraft:magma_cube", Width: 0.51, Height: 0.51},
	{JavaIdentifier: "minecraft:mangrove_boat", BedrockIdentifier: "minecraft:mangrove_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:mangrove_chest_boat", BedrockIdentifier: "minecraft:mangrove_chest_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:minecart", BedrockIdentifier: "minecraft:minecart", Width: 0.98, Height: 0.7},
	{JavaIdentifier: "minecraft:mooshroom", BedrockIdentifier: "minecraft:mooshroom", Width: 0.9, Height: 1.4},
	{JavaIdentifier: "minecraft:mule", BedrockIdentifier: "minecraft:mule", Width: 1.3965, Height: 1.6},
	{JavaIdentifier: "minecraft:oak_boat", BedrockIdentifier: "minecraft:oak_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:oak_chest_boat", BedrockIdentifier: "minecraft:oak_chest_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:ocelot", BedrockIdentifier: "minecraft:ocelot", Width: 0.6, Height: 0.7},
	{JavaIdentifier: "minecraft:ominous_item_spawner", BedrockIdentifier: "minecraft:ominous_item_spawner", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:painting", BedrockIdentifier: "minecraft:painting", Width: 0, Height: 0},
	{JavaIdentifier: "minecraft:pale_oak_boat", BedrockIdentifier: "minecraft:pale_oak_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:pale_oak_chest_boat", BedrockIdentifier: "minecraft:pale_oak_chest_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:panda", BedrockIdentifier: "minecraft:panda", Width: 1.125, Height: 1.25},
	{JavaIdentifier: "minecraft:parrot", BedrockIdentifier: "minecraft:parrot", Width: 0.5, Height: 0.9},
	{JavaIdentifier: "minecraft:phantom", BedrockIdentifier: "minecraft:phantom", Width: 0.9, Height: 0.5},
	{JavaIdentifier: "minecraft:pig", BedrockIdentifier: "minecraft:pig", Width: 0.9, Height: 0.9},
	{JavaIdentifier: "minecraft:piglin", BedrockIdentifier: "minecraft:piglin", Width: 0.6, Height: 1.95},
	{JavaIdentifier: "minecraft:piglin_brute", BedrockIdentifier: "minecraft:piglin_brute", Width: 0.6, Height: 1.95},
	{JavaIdentifier: "minecraft:pillager", BedrockIdentifier: "minecraft:pillager", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:player", BedrockIdentifier: "minecraft:player", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:polar_bear", BedrockIdentifier: "minecraft:polar_bear", Width: 1.3, Height: 1.4},
	{JavaIdentifier: "minecraft:potion", BedrockIdentifier: "minecraft:potion", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:pufferfish", BedrockIdentifier: "minecraft:pufferfish", Width: 0.7, Height: 0.7},
	{JavaIdentifier: "minecraft:rabbit", BedrockIdentifier: "minecraft:rabbit", Width: 0.4, Height: 0.5},
	{JavaIdentifier: "minecraft:ravager", BedrockIdentifier: "minecraft:ravager", Width: 1.2, Height: 1.9},
	{JavaIdentifier: "minecraft:salmon", BedrockIdentifier: "minecraft:salmon", Width: 0.7, Height: 0.5},
	{JavaIdentifier: "minecraft:sheep", BedrockIdentifier: "minecraft:sheep", Width: 0.9, Height: 1.3},
	{JavaIdentifier: "minecraft:shulker", BedrockIdentifier: "minecraft:shulker", Width: 1, Height: 1},
	{JavaIdentifier: "minecraft:shulker_bullet", BedrockIdentifier: "minecraft:shulker_bullet", Width: 0.3125, Height: 0.3125},
	{JavaIdentifier: "minecraft:silverfish", BedrockIdentifier: "minecraft:silverfish", Width: 0.4, Height: 0.3},
	{JavaIdentifier: "minecraft:skeleton", BedrockIdentifier: "minecraft:skeleton", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:skeleton_horse", BedrockIdentifier: "minecraft:skeleton_horse", Width: 1.3965, Height: 1.6},
	{JavaIdentifier: "minecraft:slime", BedrockIdentifier: "minecraft:slime", Width: 0.51, Height: 0.51},
	{JavaIdentifier: "minecraft:small_fireball", BedrockIdentifier: "minecraft:small_fireball", Width: 0.3125, Height: 0.3125},
	{JavaIdentifier: "minecraft:sniffer", BedrockIdentifier: "minecraft:sniffer", Width: 1.9, Height: 1.75},
	{JavaIdentifier: "minecraft:snow_golem", BedrockIdentifier: "minecraft:snow_golem", Width: 0.7, Height: 1.9},
	{JavaIdentifier: "minecraft:snowball", BedrockIdentifier: "minecraft:snowball", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:spawner_minecart", BedrockIdentifier: "minecraft:spawner_minecart", Width: 0.98, Height: 0.7},
	{JavaIdentifier: "minecraft:spectral_arrow", BedrockIdentifier: "minecraft:spectral_arrow", Width: 0.25, Height: 0.25},
	{JavaIdentifier: "minecraft:spider", BedrockIdentifier: "minecraft:spider", Width: 1.4, Height: 0.9},
	{JavaIdentifier: "minecraft:spruce_boat", BedrockIdentifier: "minecraft:spruce_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:spruce_chest_boat", BedrockIdentifier: "minecraft:spruce_chest_boat", Width: 1.6, Height: 0.6},
	{JavaIdentifier: "minecraft:squid", BedrockIdentifier: "minecraft:squid", Width: 0.8, Height: 0.8},
	{JavaIdentifier: "minecraft:stray", BedrockIdentifier: "minecraft:stray", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:strider", BedrockIdentifier: "minecraft:strider", Width: 0.9, Height: 1.7},
	{JavaIdentifier: "minecraft:tadpole", BedrockIdentifier: "minecraft:tadpole", Width: 0.4, Height: 0.3},
	{JavaIdentifier: "minecraft:text_display", BedrockIdentifier: "minecraft:text_display", Width: 0, Height: 0},
	{JavaIdentifier: "minecraft:tnt", BedrockIdentifier: "minecraft:tnt", Width: 0.98, Height: 0.98},
	{JavaIdentifier: "minecraft:tnt_minecart", BedrockIdentifier: "minecraft:tnt_minecart", Width: 0.98, Height: 0.7},
	{JavaIdentifier: "minecraft:trader_llama", BedrockIdentifier: "minecraft:trader_llama", Width: 0.9, Height: 1.87},
	{JavaIdentifier: "minecraft:trident", BedrockIdentifier: "minecraft:trident", Width: 0, Height: 0},
	{JavaIdentifier: "minecraft:tropical_fish", BedrockIdentifier: "minecraft:tropicalfish", Width: 0.6, Height: 0.6},
	{JavaIdentifier: "minecraft:turtle", BedrockIdentifier: "minecraft:turtle", Width: 1.2, Height: 0.4},
	{JavaIdentifier: "minecraft:vex", BedrockIdentifier: "minecraft:vex", Width: 0.4, Height: 0.8},
	{JavaIdentifier: "minecraft:villager", BedrockIdentifier: "minecraft:villager_v2", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:vindicator", BedrockIdentifier: "minecraft:vindicator", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:wandering_trader", BedrockIdentifier: "minecraft:wandering_trader", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:warden", BedrockIdentifier: "minecraft:warden", Width: 0.9, Height: 2.9},
	{JavaIdentifier: "minecraft:wind_charge", BedrockIdentifier: "minecraft:wind_charge_projectile", Width: 0.3125, Height: 0.3125},
	{JavaIdentifier: "minecraft:witch", BedrockIdentifier: "minecraft:witch", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:wither", BedrockIdentifier: "minecraft:wither", Width: 0.9, Height: 3.5},
	{JavaIdentifier: "minecraft:wither_skeleton", BedrockIdentifier: "minecraft:wither_skeleton", Width: 0.7, Height: 2.4},
	{JavaIdentifier: "minecraft:wither_skull", BedrockIdentifier: "minecraft:wither_skull", Width: 0.3125, Height: 0.3125},
	{JavaIdentifier: "minecraft:wolf", BedrockIdentifier: "minecraft:wolf", Width: 0.6, Height: 0.85},
	{JavaIdentifier: "minecraft:zoglin", BedrockIdentifier: "minecraft:zoglin", Width: 1.3965, Height: 1.4},
	{JavaIdentifier: "minecraft:zombie", BedrockIdentifier: "minecraft:zombie", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:zombie_horse", BedrockIdentifier: "minecraft:zombie_horse", Width: 1.3965, Height: 1.6},
	{JavaIdentifier: "minecraft:zombie_villager", BedrockIdentifier: "minecraft:zombie_villager_v2", Width: 0.6, Height: 1.8},
	{JavaIdentifier: "minecraft:zombified_piglin", BedrockIdentifier: "minecraft:zombie_pigman", Width: 0.6, Height: 1.95},
}

// Java1214EntityDisplayDimensionOmissions records Java identifiers in the
// versioned registry for which Geyser has no network entity definition.
var Java1214EntityDisplayDimensionOmissions = []string{
	"minecraft:block_display", // no network definition in Geyser VanillaEntities.java
	"minecraft:item_display",  // no network definition in Geyser VanillaEntities.java
	"minecraft:marker",        // no network definition in Geyser VanillaEntities.java
}

// BedrockEntityDisplayDimensions resolves a Java identifier and its normalized
// Bedrock alias to Geyser's versioned display dimensions.
func BedrockEntityDisplayDimensions(javaIdentifier, bedrockIdentifier string) (EntityDisplayDimensions, bool) {
	javaIdentifier = namespacedEntityIdentifier(javaIdentifier)
	bedrockIdentifier = namespacedEntityIdentifier(bedrockIdentifier)
	for _, dimensions := range Java1214EntityDisplayDimensions {
		if dimensions.JavaIdentifier == javaIdentifier || dimensions.BedrockIdentifier == bedrockIdentifier {
			return dimensions, true
		}
	}
	return EntityDisplayDimensions{}, false
}

func namespacedEntityIdentifier(identifier string) string {
	if identifier != "" && !strings.Contains(identifier, ":") {
		return "minecraft:" + identifier
	}
	return identifier
}
